[package]
name = "v86-wasi"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
wasmtime = "1"
lazy_static = "1.4.0"
chrono = "0.4"
rand = "0.8"
tokio = {version = "1", features = ["rt", "net", "time", "io-util"]}
tokio-tungstenite = "0.17.2"
futures-util = "0.3"
crossbeam-channel = "0.5"
json = "0.12"
tun = "0.5.4"