on:
  workflow_dispatch:

name: Build

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        run: |
          echo "test"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-v86-wasi
          path: |
            target/release
            term/
            !target/release/build
            !target/release/deps
            !target/release/examples
            !target/release/incremental
         